<?php
use bigwhoop\NBATitleBelt\Team;
use bigwhoop\NBATitleBelt\Game;
use bigwhoop\NBATitleBelt\BeltGame;
use bigwhoop\NBATitleBelt\TeamStats;

/** @var array $availableSeasons */
$availableSeasons  = $this->get('availableSeasons');

/** @var Team $beltHolder */
$beltHolder        = $this->get('beltHolder');

/** @var Team $lastYearsNBAChamp */
$lastYearsNBAChamp = $availableSeasons[$this->get('season')]['defendingChamp'];

/** @var Team|null $thisYearsNBAChamp */
$thisYearsNBAChamp = array_key_exists($this->get('season') + 1, $availableSeasons)
                   ? $availableSeasons[$this->get('season') + 1]['defendingChamp']
                   : null;

/** @var Game|null $upcomingChampGame */
$upcomingChampGame = $this->get('upcomingGame');

/** @var Game|null $upcomingChampGameIfHomeTeamWins */
$upcomingChampGameIfHomeTeamWins = $this->get('upcomingChampGameIfHomeTeamWins');

/** @var Game|null $upcomingChampGameIfAwayTeamWins */
$upcomingChampGameIfAwayTeamWins = $this->get('upcomingChampGameIfAwayTeamWins');

/** @var bool $isOngoingSeason */
$isOngoingSeason   = $this->get('isOngoingSeason'); 

/**
 * @param Team $team
 * @return string
 */
function getTeamLogoURL(Team $team) {
    return '/img/teams/' . $team->getName() . '.gif';
}

/**
 * @param Team $team
 * @return string
 */
function getTeamLogoImgTag(Team $team) {
    return '<img src="' . getTeamLogoURL($team) . '" alt="' . $team->getName() . '">';
}
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>NBA Championship Belt <?= $this->get('season'); ?>/<?= $this->get('season') + 1; ?></title>
        <link rel="shortcut icon" href="/favicon.ico">
        <style>
            * { margin: 0; padding: 0; }
            html, body { width: 100%; height: 100%; }
            
            body {
                font-family: Arial, sans-serif;
                font-size: 12px;
            }
            
            #container {
                margin: 20px;
            }
            
            #logo {
                width: 300px;
                height: 202px;
                margin-bottom: 40px;
                background: url(/img/logo.png) no-repeat;
            }
            
            h1 { font-weight: normal; font-size: 38px; margin: 50px 0 5px 0; }
            h2 { font-weight: normal; font-size: 16px; margin: 16px 0 8px 0; text-transform: uppercase; }
            
            li { margin-left: 20px; }
            a { color: #333; }
            
            .champs p img { vertical-align: middle; }
            .champs p { line-height: 24px; }
            
            .seasons { margin: 0 0 20px 0; max-width: 400px; }
            .title-winner { font-size: 32px; }
            
            .next-battle { margin: 30px 0; text-align: center; }
            .next-battle .matchup { font-size: 32px; margin-bottom: 8px; }
            .next-battle .matchup img { vertical-align: baseline; }
            .next-battle .date { font-size: 16px; }
            
            .next-battles-after-team-win { text-align: center; margin: 20px 10px; }
            .next-battle-after-team-win {
                display: inline-block;
                padding: 10px;
                margin: 0 5px;
                background-color: #f5f5f5;
                border-radius: 4px;
            }
            .next-battle-after-team-win .matchup { font-size: 16px; margin-bottom: 4px; }
            .next-battle-after-team-win .matchup img { vertical-align: top; }
            .next-battle-after-team-win .date { font-size: 10px; }
            .next-battle-after-away-team-win {  }
            
            table { border-collapse: collapse; }
            th, td { border: 1px solid #666; padding: 2px 4px; text-align: left; }
            th { background-color: #777; color: #fff; }
            th[colspan] { text-align: center; }
            td img { vertical-align: middle; }
            tr { background-color: #fff; }
            tr:nth-child(even) { background-color: #f5f5f5; }
            th.numeric, td.numeric { text-align: center; }
            
            .row   { float: left; margin: 0 50px 20px 0; }
            .clear { clear: left; }
        </style>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            
            ga('create', 'UA-45376063-1', 'nbachampionshipbelt.com');
            ga('send', 'pageview');
        </script>
    </head>
    <body>
        <div id="container">
            <div id="logo" class="row"></div>
            
            <div class="row">
                <h1>NBA Championship Belt <?= $this->get('season'); ?>/<?= $this->get('season') + 1; ?></h1>
                
                <p class="seasons">
                    <?php foreach (array_keys($availableSeasons) as $season): ?>
                        <?php if ($season == $this->get('season')): ?>
                            <?= $season; ?>/<?= $season + 1; ?>
                        <?php else: ?>
                            <a href="?season=<?= $season; ?>"><?= $season; ?>/<?= $season + 1; ?></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </p>
            </div>
            
            <div class="clear"></div>
            
            <div class="row">
                <?php if ($isOngoingSeason): ?>
                    <h2>Holder of Champ. Belt</h2>
                <?php else: ?>
                    <h2>Winner of Champ. Belt</h2>
                <?php endif; ?>
                <div class="title-winner">
                    <?= getTeamLogoImgTag($beltHolder); ?>
                    <?= $beltHolder->getName(); ?>
                </div>
            </div>
            
            <div class="row">
                <h2>NBA Champs</h2>
                <div class="champs">
                    <p>
                        <?= getTeamLogoImgTag($lastYearsNBAChamp); ?> <?= $lastYearsNBAChamp->getName(); ?>
                        (<?= $this->get('season') - 1; ?>/<?= $this->get('season'); ?>)
                    </p>
                    <p>
                        <?php if ($thisYearsNBAChamp): ?>
                            <?= getTeamLogoImgTag($thisYearsNBAChamp); ?> <?= $thisYearsNBAChamp->getName(); ?>
                        <?php else: ?>
                            TBD.
                        <?php endif; ?>
                        (<?= $this->get('season'); ?>/<?= $this->get('season') + 1; ?>)
                    </p>
                </div>
            </div>
            
            <div class="row">
                <h2>Rules</h2>
                <ul>
                    <li>It starts with the first game of last season's NBA champion.</li>
                    <li>If the belt holding team gets beat it loses the belt to the other team.</li>
                    <li>No playoffs, the race is over after the regular season.</li>
                </ul>
            </div>
            
            <div class="row">
                <h2>Data Sources</h2>
                <p>
                    Idea: <a href="http://www.reddit.com/r/nba/comments/1pn9t2/can_we_keep_track_of_the_owner_of_the/">/u/hckygod91 on reddit</a><br>
                    Scores: <a href="http://www.basketball-reference.com/">basketball-reference.com</a><br>
                    Logos: <a href="http://www.nba.com/">nba.com</a><br>
                    Contribute: <a href="https://github.com/bigwhoop/nbachampionshipbelt">bigwhoop/nbachampionshipbelt</a>
                </p>
            </div>
            
            <div class="clear"></div>
        
            <div class="row">
                <h2>Game Log</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Home Team</th>
                            <th>Score</th>
                            <th>Away Team</th>
                            <th>Winner</th>
                            <th>Streak</th>
                            <th>Wins</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->get('gameLog') as $beltGame): ?>
                            <?php
                            /** @var BeltGame $beltGame */
                            $game = $beltGame->getGame();
                            $newBeltHolder = $beltGame->getBeltHolderAfterGame();
                            ?>
                            <tr>
                                <td><?= $game->getDate()->format('Y-m-d'); ?></td>
                                <td><?= $game->getHomeTeam()->getName(); ?></td>
                                <td><?= $game->getScore();; ?></td>
                                <td><?= $game->getAwayTeam()->getName(); ?></td>
                                <td><?= getTeamLogoImgTag($newBeltHolder); ?> <?= $newBeltHolder->getName(); ?></td>
                                <td><?= $beltGame->getWinStreak(); ?></td>
                                <td><?= $beltGame->getAccumulatedWins(); ?></td>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                
                <?php if ($upcomingChampGame): ?>
                    <div class="next-battle">
                        <h2>Next Battle for the Belt</h2>
                        
                        <div class="matchup">
                            <?= getTeamLogoImgTag($upcomingChampGame->getAwayTeam()); ?>
                            <?= $upcomingChampGame->getAwayTeam()->getName(); ?>
                            @
                            <?= getTeamLogoImgTag($upcomingChampGame->getHomeTeam()); ?>
                            <?= $upcomingChampGame->getHomeTeam()->getName(); ?>
                        </div>
                        <div class="date">
                            <?= $upcomingChampGame->getDate()->format('Y-m-d'); ?>
                        </div>
                    </div>
                    
                    <div class="next-battles-after-team-win">
                        <div class="next-battle-after-team-win next-battle-after-away-team-win">
                            <?php if ($upcomingChampGameIfHomeTeamWins): ?>
                                <div class="matchup">
                                    <?= getTeamLogoImgTag($upcomingChampGameIfAwayTeamWins->getAwayTeam()); ?>
                                    @
                                    <?= getTeamLogoImgTag($upcomingChampGameIfAwayTeamWins->getHomeTeam()); ?>
                                </div>
                                <div class="date">
                                    <?= $upcomingChampGameIfAwayTeamWins->getDate()->format('Y-m-d'); ?>
                                </div>
                            <?php else: ?>
                                <p>No more games!</p>
                            <?php endif; ?>
                        </div>
                    
                        <div class="next-battle-after-team-win next-battle-after-home-team-win">
                            <?php if ($upcomingChampGameIfHomeTeamWins): ?>
                                <div class="matchup">
                                    <?= getTeamLogoImgTag($upcomingChampGameIfHomeTeamWins->getAwayTeam()); ?>
                                    @
                                    <?= getTeamLogoImgTag($upcomingChampGameIfHomeTeamWins->getHomeTeam()); ?>
                                </div>
                                <div class="date">
                                    <?= $upcomingChampGameIfHomeTeamWins->getDate()->format('Y-m-d'); ?>
                                </div>
                            <?php else: ?>
                                <p>No more games!</p>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            
            <div class="row">
                <h2>Stats</h2>
                <table>
                    <thead>
                        <tr>
                            <th rowspan="2">Rank</th>
                            <th rowspan="2">Team</th>
                            <th rowspan="2" class="numeric">Games</th>
                            <th colspan="3" class="numeric">Wins</th>
                            <th colspan="3" class="numeric">Losses</th>
                            <th rowspan="2">Win %</th>
                        </tr>
                        <tr>
                            <th class="numeric">Total</th>
                            <th class="numeric"><small title="As Challenger">As Chall.</small></th>
                            <th class="numeric"><small title="As Defender">As Def.</small></th>
                            <th class="numeric">Total</th>
                            <th class="numeric"><small title="As Challenger">As Chall.</small></th>
                            <th class="numeric"><small title="As Defender">As Def.</small></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $rank = 1; $prevWinPercentage = $prevNumGames = null; ?>
                        <?php foreach ($this->get('stats') as $teamStats): ?>
                            <?php /** @var TeamStats $teamStats */ ?>
                            <tr>
                                <td>
                                    <?php
                                    $numGames = $teamStats->countGames();
                                    $winPercentage = $teamStats->calcWinPercentage();
                                    
                                    if ($prevWinPercentage !== $winPercentage || $prevNumGames !== $numGames) {
                                        echo $rank . '.';
                                        $prevNumGames = $numGames;
                                        $prevWinPercentage = $winPercentage;
                                    }
                                    $rank++;
                                    ?>
                                </td>
                                <td><?= getTeamLogoImgTag($teamStats->getTeam()); ?> <?= $teamStats->getTeam()->getName(); ?></td>
                                <td class="numeric"><?= $numGames; ?></td>
                                <td class="numeric"><?= $teamStats->countWins(); ?></td>
                                <td class="numeric"><small><?= $teamStats->countWinsAsChallenger(); ?></small></td>
                                <td class="numeric"><small><?= $teamStats->countWinsAsDefender(); ?></small></td>
                                <td class="numeric"><?= $teamStats->countLosses(); ?></td>
                                <td class="numeric"><small><?= $teamStats->countLossesAsChallenger(); ?></small></td>
                                <td class="numeric"><small><?= $teamStats->countLossesAsDefender(); ?></small></td>
                                <td><?= $winPercentage; ?>%</td>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            
            <div class="clear"></div>
        </div>
    </body>
</html>