<!DOCTYPE html>
<html>
    <head>
        <title>Season Not Found</title>
        <style>
            * { margin: 0; padding: 0; }
            html, body { width: 100%; height: 100%; }
            
            body {
                font-family: Arial, sans-serif;
                font-size: 12px;
            }
            
            #container { margin: 20px; }
            h1 { font-weight: normal; font-size: 38px; margin: 0 0 5px 0; }
            a { color: #333; }
        </style>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            
            ga('create', 'UA-45376063-1', 'nbachampionshipbelt.com');
            ga('send', 'pageview');
        </script>
    </head>
    <body>
        <div id="container">
            <h1>Season Not Found</h1>
            
            <p>No data for this season available.</p>
            <p>
                <a href="/">Go back to the start page.</a>
            </p>
        </div>
    </body>
</html>